version: '3.8'

services:
  db:
    image: postgres
    env_file: ./.env
    ports:
      - "${POSTGRESS_LOCAL_PORT}:${POSTGRESS_DOCKER_PORT}"
    environment:
      POSTGRES_USER: $POSTGRESS_USERNAME
      POSTGRES_PASSWORD: $POSTGRESS_PASSWORD
      POSTGRES_DB: $POSTGRESS_DB_NAME

  app:
    depends_on:
      - db
    build: ./
    env_file: ./.env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:postgresql://db:$POSTGRESS_DOCKER_PORT/$POSTGRESS_DB_NAME",
        "spring.datasource.username" : "$POSTGRESS_USERNAME",
        "spring.datasource.password" : "$POSTGRESS_PASSWORD"
      }'